service: welcome-service
variablesResolutionMode: 20210326
projectDir: ..

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-slic-watch-plugin
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${env:TARGET_REGION}'}
  tracing:
    lambda: true
  environment:
    SLIC_STAGE: ${self:provider.stage}
  logRetentionInDays: 7

custom:
  app: ${file(../app.yml)}
  bundle:
    esbuild: true
    linting: false
  emailQueueName: ${self:provider.stage}-email-queue
  prune:
    automatic: true
    number: 3
  serverless-offline:
    httpPort: 4012
    lambdaPort: 4014
    websocketPort: 4013
    stage: local
    region: ${self:provider.region}
  slicWatch: ${self:custom.app.slicWatch}

functions: ${file(./sls-functions.yml)}
